export const defaultEncouragements = [
  "🎩 There is no rest for you in this world. perhaps in the next. 🔫🔪",
  "My fury is a thing to behold",
  "Nice Job! 🎇",
  "Way to go! ✨",
  "Wow, nice change! 💗",
  "So good! 💖",
  "Bravo! 👏",
  "You rock! 🚀",
  "Well done! 🎉",
  "I see what you did there! 🙏",
  "Genius work! 🍩",
  "Thumbs up! 👍",
  "Coding win! 🍸",
  "FTW! ⚡️",
  "Yep! 🙆",
  "Nnnnnnnailed it! ✌",
  "You're good enough! 😎",
  "You're smart enough! 💫",
  "People like you! 💞",
];

export const defaultDiscouragements = [
  "😱 Seriously?",
  "😷 That's a bad look.",
  "Burn it to the ground! 🔥",
  "😠 Torvalds frowns at you.",
  "🚶 Have you considered another career?",
  "You must hate your coworkers. 👹",
  "😡 You must hate yourself.",
  "Ha! Yeah, that'll work. 😄",
  "Are you just hitting keys at random?",
  "You code like a PM. 😐",
  "🍸 Are you drinking?",
  "Who cares about uptime anyways, amirite?! 😏",
  "✨ YOLO! ✨",
  "🎻 Today isn't your day, is it? 🐺⚔️",
  "🎩 There is no rest for you in this world. perhaps in the next. 🔫🔪",
  "🥃 I know what this is. It’s just you, talking to yourself, about yourself. 🤪",
  "Being stupid is only painful for others.",
  "Intelligence is a very valuable thing, innit, my friend.",
  "I know what I know, you know. If you don't know, then you don't know, do you?",
  "🔫🔪 Si vis pacem, para bellum 🔫🔪",
  "🔫👼 Ça va sans dire",
];
